routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/admin/login', ['as' => 'login', 'uses' => 'App\Http\Controllers\Auth\LoginController@showLoginForm']);
Route::post('/admin/login', ['uses' => 'App\Http\Controllers\Auth\LoginController@login']);
Route::post('/admin/logout', ['as' => 'login', 'uses' => 'App\Http\Controllers\Auth\LoginController@logout']);

Route::group(['as' => 'admin.', 'prefix' => '/admin', 'middleware' => ['auth', 'is.admin']], function() {

    Route::get('/', ['as' => 'home', 'uses' => 'Admin\\HomeController@index']);

    Route::group(['as' => 'users.', 'prefix' => '/users'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\UsersController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\UsersController@create']);
        Route::get('/{user}', ['as' => 'edit', 'uses' => 'Admin\\UsersController@edit']);
        Route::put('/{user}', ['as' => 'update', 'uses' => 'Admin\\UsersController@update']);
        Route::delete('/{user}', ['as' => 'destroy', 'uses' => 'Admin\\UsersController@destroy']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\UsersController@store']);
    });

    Route::group(['as' => 'mentors.', 'prefix' => '/mentors'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\MentorsController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\MentorsController@create']);
        Route::get('/{user}', ['as' => 'edit', 'uses' => 'Admin\\MentorsController@edit']);
        Route::put('/{user}', ['as' => 'update', 'uses' => 'Admin\\MentorsController@update']);
        Route::delete('/{user}', ['as' => 'destroy', 'uses' => 'Admin\\MentorsController@destroy']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\MentorsController@store']);
    });

    Route::group(['as' => 'news.', 'prefix' => '/news'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\NewsController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\NewsController@create']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\NewsController@store']);
        Route::get('/{news}', ['as' => 'edit', 'uses' => 'Admin\\NewsController@edit']);
        Route::put('/{news}', ['as' => 'update', 'uses' => 'Admin\\NewsController@update']);
        Route::delete('/{news}', ['as' => 'destroy', 'uses' => 'Admin\\NewsController@destroy']);
    });

    Route::group(['as' => 'questionnaire.', 'prefix' => '/questionnaire'], function() {
        Route::get('/{q}', ['as' => 'index', 'uses' => 'Admin\\QuestionnaireController@index']);
//        Route::get('/{q}', ['as' => 'edit', 'uses' => 'Admin\\QuestionnaireController@edit']);
//        Route::put('/{q}', ['as' => 'update', 'uses' => 'Admin\\QuestionnaireController@update']);
    });

    Route::group(['as' => 'reports.', 'prefix' => '/reports'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\ReportsController@index']);
        Route::get('/{report}', ['as' => 'edit', 'uses' => 'Admin\\ReportsController@edit']);
        Route::put('/{report}', ['as' => 'update', 'uses' => 'Admin\\ReportsController@update']);
    });
});

app/Http/Controllers/Admin/MentorsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Roles;
use App\Http\Controllers\Controller;
use App\Models\City;
use App\Models\User;
use App\Services\UsersService;
use Illuminate\Http\Request;

class MentorsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(UsersService $usersService)
    {
        $user = \Auth::user();
        $users = $usersService->query()->with('profile')
            ->when($user->isAdmin(), function ($query) use ($user) {
                $query->join('questionnaires', 'questionnaires.user_id', '=', 'users.id')
                    ->where('questionnaires.city_id', '=', $user->city_id)
                    ->select('users.*');
            })
            ->whereIn('role', [
                Roles::USER,
                Roles::MENTOR
            ])
            ->orderBy('users.id', 'desc')
            ->paginate(15);

        return view('mentors.index', [
            'users' => $users
        ]);
    }

    public function edit(User $user)
    {
        return view('mentors.edit', [
            'user' => $user,
            'roles' => Roles::mentornNames(),
            'cities' => City::query()->orderBy('name', 'ASC')->get()->all()
        ]);
    }

    public function create()
    {
        return view('mentors.create',
            [
                'roles' => Roles::mentornNames(),
                'cities' => City::query()->orderBy('name', 'ASC')->get()->all()
            ]
        );
    }

    public function update(Request $request, User $user, UsersService $usersService)
    {
        $usersService->update($user, $request->all());
        return redirect(route('admin.mentors.index'));
    }

    public function store(Request $request, UsersService $usersService)
    {
        $usersService->create($request->all());

        return redirect(route('admin.mentors.index'));
    }
}

resources/views/mentors/create.blade.php
@extends('layouts.app')
@section('title')Пользователи@endsection
@section('content')
    <form action="{!! route('admin.users.store') !!}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Добавление пользователя</h3>
                    </div>
                    <div class="box-body">

                        <div class="form-group">
                            <label>Имя:</label>
                            <input type="text" name="name" class="form-control" value="{{ @old('name') }}">
                        </div>

                        <div class="form-group">
                            <label>Email:</label>
                            <input type="text" name="email" class="form-control" value="{{ @old('email') }}">
                        </div>

                        <div class="form-group">
                            <label>Роль:</label>
                            <select class="form-control" name="role">
                                @foreach($roles as $key => $value)
                                    <option value="{!! $key !!}">{!! $value !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Город:</label>
                            <select class="form-control" name="city_id">
                                @foreach($cities as $key => $value)
                                    <option value="{!! $value->id !!}" >{!! $value->name !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Пароль:</label>
                            <input type="password" name="password" class="form-control" value="">
                        </div>

                        <div class="form-group">
                            <label>Подтверждение пароля:</label>
                            <input type="password" name="password_confirmation" class="form-control" value="">
                        </div>


                        <button type="submit" class="btn btn-success pull-right">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('page.footer.scripts')
    <script>

    </script>
@endpush

resources/views/mentors/edit.blade.php
@extends('layouts.app')
@section('title')Пользователи@endsection
@section('content')
    <form action="{!! route('admin.users.update', [
        'user' => $user->getKey()
    ]) !!}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="PUT">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Редактирование пользователя</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <label>Имя</label>
                            <input type="text" name="name" class="form-control" value="{{ @old('name') ?? $user->name }}">
                        </div>

                        <div class="form-group">
                            <label>Email:</label>
                            <input type="text" name="email" class="form-control" value="{{ @old('email') ?? $user->email }}">
                        </div>

                        <div class="form-group">
                            <label>Роль:</label>
                            <select class="form-control" name="role">
                                @foreach($roles as $key => $value)
                                    <option value="{!! $key !!}" {!! $user->role == $key ? 'selected':'' !!}>{!! $value !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Город:</label>
                            <select class="form-control" name="city_id">
                                @foreach($cities as $key => $value)
                                    <option value="{!! $value->id !!}" {!! $user->city_id == $value->id ? 'selected':'' !!}>{!! $value->name !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Пароль:</label>
                            <input type="password" name="password" class="form-control" value="">
                        </div>

                        <div class="form-group">
                            <label>Подтверждение пароля:</label>
                            <input type="password" name="password_confirmation" class="form-control" value="">
                        </div>

                        <button type="submit" class="btn btn-success pull-right">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('page.footer.scripts')
    <script>

    </script>
@endpush

resources/views/mentors/index.blade.php
@extends('layouts.app')
@section('title')Наставники@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Наставники и кандидаты (@if(\Auth::user()->isSuperAdmin())Все города@else{{\Auth::user()->city->name}}@endif)</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Статус</th>
                            <th>Город</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>
                                    {{ $user->name }}
                                </td>
                                <td>
                                    {{ \App\Helpers\Roles::getName($user->role) }}
                                </td>
                                <td>
                                    {{ $user->profile->city->name }}
                                </td>
                                <td>
                                    <a target="_blank" href="{{ route('admin.questionnaire.index', ['id' => $user->profile->id]) }}">Анкета</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form id="usersDelete" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="DELETE">
    </form>
@endsection

@push('page.footer.scripts')
    <script></script>
@endpush