routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/admin/login', ['as' => 'login', 'uses' => 'App\Http\Controllers\Auth\LoginController@showLoginForm']);
Route::post('/admin/login', ['uses' => 'App\Http\Controllers\Auth\LoginController@login']);
Route::post('/admin/logout', ['as' => 'login', 'uses' => 'App\Http\Controllers\Auth\LoginController@logout']);

Route::group(['as' => 'admin.', 'prefix' => '/admin', 'middleware' => ['auth', 'is.admin']], function() {

    Route::get('/', ['as' => 'home', 'uses' => 'Admin\\HomeController@index']);

    Route::group(['as' => 'users.', 'prefix' => '/users'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\UsersController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\UsersController@create']);
        Route::get('/{user}', ['as' => 'edit', 'uses' => 'Admin\\UsersController@edit']);
        Route::put('/{user}', ['as' => 'update', 'uses' => 'Admin\\UsersController@update']);
        Route::delete('/{user}', ['as' => 'destroy', 'uses' => 'Admin\\UsersController@destroy']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\UsersController@store']);
    });

    Route::group(['as' => 'mentors.', 'prefix' => '/mentors'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\MentorsController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\MentorsController@create']);
        Route::get('/{user}', ['as' => 'edit', 'uses' => 'Admin\\MentorsController@edit']);
        Route::put('/{user}', ['as' => 'update', 'uses' => 'Admin\\MentorsController@update']);
        Route::delete('/{user}', ['as' => 'destroy', 'uses' => 'Admin\\MentorsController@destroy']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\MentorsController@store']);
    });

    Route::group(['as' => 'news.', 'prefix' => '/news'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\NewsController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\NewsController@create']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\NewsController@store']);
        Route::get('/{news}', ['as' => 'edit', 'uses' => 'Admin\\NewsController@edit']);
        Route::put('/{news}', ['as' => 'update', 'uses' => 'Admin\\NewsController@update']);
        Route::delete('/{news}', ['as' => 'destroy', 'uses' => 'Admin\\NewsController@destroy']);
    });

    Route::group(['as' => 'questionnaire.', 'prefix' => '/questionnaire'], function() {
        Route::get('/{q}', ['as' => 'index', 'uses' => 'Admin\\QuestionnaireController@index']);
//        Route::get('/{q}', ['as' => 'edit', 'uses' => 'Admin\\QuestionnaireController@edit']);
//        Route::put('/{q}', ['as' => 'update', 'uses' => 'Admin\\QuestionnaireController@update']);
    });

    Route::group(['as' => 'reports.', 'prefix' => '/reports'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\ReportsController@index']);
        Route::get('/{report}', ['as' => 'edit', 'uses' => 'Admin\\ReportsController@edit']);
        Route::put('/{report}', ['as' => 'update', 'uses' => 'Admin\\ReportsController@update']);
    });
});

app/Models/Report.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Report extends Model
{
    protected $table = 'reports';

    protected $fillable = [
        'dates',
        'description',
        'rating_children_before',
        'rating_children_after',
        'rating_after',
        'target',
        'comment',
        'photos'
    ];

    protected $casts = [
        'dates' => 'json',
        'rating_children_before' => 'integer',
        'rating_children_after' => 'integer',
        'rating_after' => 'integer',
        'photos' => 'json'
    ];

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function getPhotosAttribute($value)
    {
        if (empty($value)) {
            return null;
        }

        return array_map(function($file) {
            return Storage::url($file);
        }, json_decode($value, true));
    }
}

app/Http/Controllers/Admin/ReportsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Report;
use App\Services\ReportsService;
use Illuminate\Http\Request;

class ReportsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(ReportsService $reportsService)
    {
        $reports = $reportsService->query()
            ->orderBy('id', 'desc')
            ->paginate(15);

        return view('reports.index', [
            'reports' => $reports
        ]);
    }

    public function edit(Report $report)
    {
        return view('reports.edit', [
            'report' => $report
        ]);
    }
}

app/Http/Controllers/ReportsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Reports\CreateRequest;
use App\Http\Requests\Reports\IndexRequest;
use App\Services\ReportsService;
use Illuminate\Foundation\Validation\ValidatesRequests;

class ReportsController extends Controller
{
    use ValidatesRequests;

    public function index(IndexRequest $request, ReportsService $reportsService)
    {
        $reports = $reportsService->query()
            ->where('user_id', '=', $request->user()->getKey())
            ->get();

        return response()->json([
            'reports' => $reports
        ]);
    }

    public function create(CreateRequest $request, ReportsService $reportsService)
    {
        $this->validate($request, [
            'dates' => 'required|array',
            'dates.*' => 'required|date',
            'description' => 'required|string',
            'rating_children_before' => 'required|integer',
            'rating_children_after' => 'required|integer',
            'rating_after' => 'required|integer',
            'target' => 'required|string',
            'comment' => 'nullable|string',
            'photos' => 'array|nullable',
            'photos.*' => 'image'
        ]);

        return $reportsService->create($request->user(), $request->all(), $request->file('photos'));
    }
}

resources/views/reports/edit.blade.php
@extends('layouts.app')
@section('title')Отчет@endsection
@section('content')
    <form action="{!! route('admin.reports.update', [
        'user' => $report->getKey()
    ]) !!}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="PUT">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Отчет</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <label>Даты:</label> {{ implode(', ', $report->dates) }}
                        </div>

                        <div class="form-group">
                            <label>Чем занимались на встече:</label> {{ $report->description }}
                        </div>

                        <div class="form-group">
                            <label>Оценка настроения ребенка до встречи:</label> {{ $report->rating_children_before }}
                        </div>

                        <div class="form-group">
                            <label>Оценка настроения ребенка после встречи:</label> {{ $report->rating_children_after }}
                        </div>

                        <div class="form-group">
                            <label>Оценка настроения после встречи:</label> {{ $report->rating_after }}
                        </div>

                        <div class="form-group">
                            <label>Цель на следующую встречу :</label> {{ $report->target }}
                        </div>

                        <div class="form-group">
                            <label>Комментарии :</label> {{ $report->comment }}
                        </div>

                        <div class="form-group">
                            <label>Фотографии :</label>
                            @foreach($report->photos as $photo)
                                <img src="{!! $photo; !!}">
                            @endforeach
                        </div>

                        <button type="submit" class="btn btn-success pull-right">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('page.footer.scripts')
    <script></script>
@endpush

resources/views/reports/index.blade.php
@extends('layouts.app')
@section('title')Отчеты@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Отчеты</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название</th>
                            <th>Тип</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($reports as $report)
                            <tr>
                                <td>
                                    {!! $report->getKey() !!}
                                </td>
                                <td>
                                    <a href="{!! route('admin.reports.edit', [
                                        'user' => $report->getKey()
                                    ]) !!}">
                                        {!! implode(', ', $report->dates) !!}
                                    </a>
                                </td>
                                <td>
                                    <a href="{!! route('admin.reports.edit', [
                                        'user' => $report->getKey()
                                    ]) !!}">
                                        {{ $report->user->profile->name }} {{ $report->user->profile->surname }}
                                    </a>
                                </td>
                                <td>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('page.footer.scripts')
    <script></script>
@endpush