routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/admin/login', ['as' => 'login', 'uses' => 'App\Http\Controllers\Auth\LoginController@showLoginForm']);
Route::post('/admin/login', ['uses' => 'App\Http\Controllers\Auth\LoginController@login']);
Route::post('/admin/logout', ['as' => 'login', 'uses' => 'App\Http\Controllers\Auth\LoginController@logout']);

Route::group(['as' => 'admin.', 'prefix' => '/admin', 'middleware' => ['auth', 'is.admin']], function() {

    Route::get('/', ['as' => 'home', 'uses' => 'Admin\\HomeController@index']);

    Route::group(['as' => 'users.', 'prefix' => '/users'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\UsersController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\UsersController@create']);
        Route::get('/{user}', ['as' => 'edit', 'uses' => 'Admin\\UsersController@edit']);
        Route::put('/{user}', ['as' => 'update', 'uses' => 'Admin\\UsersController@update']);
        Route::delete('/{user}', ['as' => 'destroy', 'uses' => 'Admin\\UsersController@destroy']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\UsersController@store']);
    });

    Route::group(['as' => 'mentors.', 'prefix' => '/mentors'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\MentorsController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\MentorsController@create']);
        Route::get('/{user}', ['as' => 'edit', 'uses' => 'Admin\\MentorsController@edit']);
        Route::put('/{user}', ['as' => 'update', 'uses' => 'Admin\\MentorsController@update']);
        Route::delete('/{user}', ['as' => 'destroy', 'uses' => 'Admin\\MentorsController@destroy']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\MentorsController@store']);
    });

    Route::group(['as' => 'news.', 'prefix' => '/news'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\NewsController@index']);
        Route::get('/create', ['as' => 'create', 'uses' => 'Admin\\NewsController@create']);
        Route::post('/', ['as' => 'store', 'uses' => 'Admin\\NewsController@store']);
        Route::get('/{news}', ['as' => 'edit', 'uses' => 'Admin\\NewsController@edit']);
        Route::put('/{news}', ['as' => 'update', 'uses' => 'Admin\\NewsController@update']);
        Route::delete('/{news}', ['as' => 'destroy', 'uses' => 'Admin\\NewsController@destroy']);
    });

    Route::group(['as' => 'questionnaire.', 'prefix' => '/questionnaire'], function() {
        Route::get('/{q}', ['as' => 'index', 'uses' => 'Admin\\QuestionnaireController@index']);
//        Route::get('/{q}', ['as' => 'edit', 'uses' => 'Admin\\QuestionnaireController@edit']);
//        Route::put('/{q}', ['as' => 'update', 'uses' => 'Admin\\QuestionnaireController@update']);
    });

    Route::group(['as' => 'reports.', 'prefix' => '/reports'], function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Admin\\ReportsController@index']);
        Route::get('/{report}', ['as' => 'edit', 'uses' => 'Admin\\ReportsController@edit']);
        Route::put('/{report}', ['as' => 'update', 'uses' => 'Admin\\ReportsController@update']);
    });
});

app/Models/Message.php
<?php

namespace App\Models;

use App\Helpers\MessagesTypes;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $fillable = [
        'to',
        'from',
        'type',
        'content'
    ];

    public function getContentAttribute($value)
    {
        switch ($this->type) {
        case MessagesTypes::TEXT:
            return $value;
            break;
        case MessagesTypes::REPORT:
            return Report::find((int)$value);
        }
        return $value;
    }

    public function getCreatedAtAttribute($value)
    {
        if (strtotime($value) < strtotime('today')) {
            return date('d.m', strtotime($value));
        } else {
            return date('H:i', strtotime($value));
        }
    }
}

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class News extends Model
{
    protected $table = 'news';

    protected $fillable = [
        'name',
        'type',
        'image_path',
        'roles',
        'city_ids',
        'text',
    ];

    protected $casts = [
        'roles' => 'json',
        'city_ids' => 'json',
    ];

    public function getCityesAttribute()
    {
        if (empty($this->city_ids)) {
            return null;
        }

        return City::find($this->city_ids);
    }

    public function getImagePathAttribute($value)
    {
        if (empty($value)) {
            return null;
        }

        return Storage::url($value);
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\NewsTypes;
use App\Helpers\Roles;
use App\Http\Controllers\Controller;
use App\Http\Requests\News\CreateRequest;
use App\Models\City;
use App\Models\News;
use App\Services\NewsService;
use App\Services\UsersService;
use Illuminate\Http\Request;

class NewsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(NewsService $newsService)
    {
        $news = $newsService->query()
            ->orderBy('id', 'desc')
            ->paginate(15);

        return view('news.index', [
            'newses' => $news,
            'types' => NewsTypes::names()
        ]);
    }

    public function create(UsersService $usersService)
    {
        return view('news.create', [
            'types' => NewsTypes::names(),
            'roles' => Roles::names(),
            'city_ids' => City::whereIn('id', $usersService->query()->select('city_id')->whereNotNull('city_id'))->get()
        ]);
    }

    public function store(CreateRequest $request, NewsService $newsService)
    {
        try {
            $newsService->create($request->all(), $request->file('image'));

            return redirect()->route('admin.news.index')->with('message', 'Сохранено успешно!');
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors($exception->getMessage());
        }
    }

    public function edit(News $news, UsersService $usersService)
    {
        return view('news.edit', [
            'news' => $news,
            'types' => NewsTypes::names(),
            'roles' => Roles::names(),
            'city_ids' => City::whereIn('id', $usersService->query()->select('city_id')->whereNotNull('city_id'))->get()
        ]);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\News\IndexRequest;
use App\Http\Requests\News\CreateRequest;
use App\Services\NewsService;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

class NewsController extends BaseController
{
    use ValidatesRequests;

    public function index(IndexRequest $request, NewsService $newsService)
    {
        $query = $newsService->getQueryAcceptByUser($request->user())->orderBy('id', 'desc');

        return response()->json([
            'total' => $query->count(),
            'news' => $query->get()
        ]);
    }

    public function create(CreateRequest $request, NewsService $newsService)
    {
        $news = $newsService->create($request->all(), $request->file('image'));

        return response()->json([
            'id' => $news->getKey(),
            'name' => $news->name,
            'type' => $news->type,
            'text' => $news->text,
            'image_path' => $news->image_path,
            'roles' => $news->roles,
            'city_ids' => $news->city_ids,
            'cityes' => $news->cityes,
        ]);
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')
@section('title')Добавление события@endsection
@section('content')
    <form action="{!! route('admin.news.store') !!}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Добавление события</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <label>Название:</label>
                            <input type="text" name="name" class="form-control" value="{{ @old('name') }}">
                        </div>

                        <div class="form-group">
                            <label>Тип:</label>
                            <select class="form-control" name="type">
                                @foreach($types as $key=>$value)
                                    <option value="{!! $key !!}" {!! (@old('type') ?? '') ? 'selected':'' !!}>{!! $value !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Роли:</label>
                            <select multiple class="form-control" name="roles[]">
                                @foreach($roles as $key=>$value)
                                    <option value="{!! $key !!}" {!! (@old('roles') ?? '') ? 'selected':'' !!}>{!! $value !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div multiple class="form-group">
                            <label>Города:</label>
                            <select multiple class="form-control" name="city_ids[]">
                                @foreach($city_ids as $key=>$value)
                                    <option value="{!! $value->id !!}" {!! (@old('city_ids') ?? '') ? 'selected':'' !!}>{!! $value->name !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Текст:</label>
                            <textarea class="form-control" name="text">{{ @old('text') }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="inputFile">Картинка:</label>
                            <input type="file" name="image" id="inputFile" accept="image/jpeg,image/png">
                        </div>

                        <button type="submit" class="btn btn-success pull-right">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('page.footer.scripts')
    <script></script>
@endpush

resources/views/news/edit.blade.php
@extends('layouts.app')
@section('title')Добавление события@endsection
@section('content')
    <form action="{!! route('admin.news.update', [
        'news' => $news->getKey()
    ]) !!}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Добавление события</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <label>Название:</label>
                            <input type="text" name="name" class="form-control" value="{{ $news->name }}">
                        </div>

                        <div class="form-group">
                            <label>Тип:</label>
                            <select class="form-control" name="type">
                                @foreach($types as $key=>$value)
                                    <option value="{!! $key !!}" {!! ($news->type) ? 'selected':'' !!}>{!! $value !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Роли:</label>
                            <select multiple class="form-control" name="roles[]">
                                @foreach($roles as $key=>$value)
                                    <option value="{!! $key !!}" {!! in_array($key, (array) $news->roles) ? 'selected':'' !!}>{!! $value !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Города:</label>
                            <select multiple class="form-control" name="cities[]">
                                @foreach($cities as $key=>$value)
                                    <option value="{!! $key !!}" {!! in_array($key, (array) $news->cities) ? 'selected':'' !!}>{!! $value->name !!}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Текст:</label>
                            <textarea class="form-control" name="text">{{ $news->text }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="inputFile">Картинка:</label>
                            <input type="file" name="image" id="inputFile" accept="image/jpeg,image/png">
                        </div>

                        <button type="submit" class="btn btn-success pull-right">Сохранить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('page.footer.scripts')
    <script></script>
@endpush

resources/views/news/index.blade.php
@extends('layouts.app')
@section('title')События@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">События</h3>
                    <a href="{!! route('admin.news.create') !!}" class="btn btn-primary btn-xs pull-right">Добавить</a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Название</th>
                            <th>Тип</th>
                            <th>Дата</th>
{{--                            <th></th>--}}
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($newses as $news)
                            <tr>
                                <td colspan="4">
                                    <img src="{{ $news->image_path }}" width="100px" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    {{ $news->name }}
                                </td>
                                <td>
                                    {!! $types[$news->type] !!}
                                </td>
                                <td>
                                    {!! $news->created_at !!}
                                </td>
                                {{--<td>
                                    <a href="{!! route('admin.news.destroy', [
                                        'user' => $news->getKey()
                                    ]) !!}" onclick="event.preventDefault();document.getElementById('deleteForm').action = this.href;document.getElementById('deleteForm').submit();" class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>--}}
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form id="deleteForm" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="DELETE">
    </form>
@endsection

@push('page.footer.scripts')
    <script></script>
@endpush